### ISSUE TITLE
Bower Installation

### ISSUE THREAD

**Issue by bradbenetton** [tadatuta/bl-carousel#1]
Привет!
Возможно ли библиотеку ставить через Bower?

**Comment by tadatuta** [comment]
привет!
прямо сейчас можно сделать

``` sh
bower i git@github.com:tadatuta/bl-carousel.git --save
```

но, конечно, стоит добавить `bower.json`. Сделаю.

**Comment by adinvadim** [comment]
Этот блок еще актуален?

**Comment by tadatuta** [comment]
@adinvadim да, только ставить нужно из ветки `v2`
